site_name: Machine Learning Tutorials

theme:
  name: material
  features:
  - content.tabs.link
  - content.code.annotation
  - content.code.copy

  - navigation.sections
  - navigation.indexes
  - navigation.instant
  - navigation.tabs
  - navigation.top
  - navigation.tracking

  - search.suggest
  - search.highlight

  - toc.follow
  
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: lime
      accent: light blue 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: blue
      accent: lime


extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ashishbindra2
    - icon: fontawesome/brands/linkedin
      link: https://in.linkedin.com/in/ashishbindra2/


markdown_extensions:
  - sane_lists
  - md_in_html

  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition

  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  
nav:
  - Home: index.md
  - intro-to-ml-google:
    - Overview: intro-to-ml-google/index.md 
    - Supervised Learning: intro-to-ml-google/SupervisedLearning.md
    - test-1: intro-to-ml-google/test.md 
  - interview: interview.md
  - data-sci: data-sci-interview.md
  - mini-projects: mini-projects.md
  - SQL: sql.md
  - interview-ai: random.md
  - mixed: unimportant.md
    
 

      
copyright: |
  &copy; 2024 <a href="https://github.com/ashishbindra2"  target="_blank" rel="noopener">Ashish Bindra</a>